# Generated by Django 5.1.7 on 2025-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfficeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_items', models.TextField(help_text='list sub-items separated by commas')),
                ('module_type', models.CharField(choices=[('HR', 'HR Management'), ('Accounts', 'Accounts'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('IT', 'IT Asset Management'), ('Workshop', 'Workshop Management')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSpecificModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_items', models.TextField(help_text='list sub-items separated by commas')),
                ('module_type', models.CharField(choices=[('Procurement', 'Procurement'), ('QAQC', 'QA/QC'), ('QS', 'Quantity Surveying'), ('DC', 'Document Control'), ('Planning', 'Planning'), ('Store', 'Store Asset Management System'), ('HSE', 'Health, Safety, Environment')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
