# Generated by Django 5.1.7 on 2025-03-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='qs.department')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HeadOfficeModule',
        ),
        migrations.DeleteModel(
            name='ProjectSpecificModule',
        ),
        migrations.AddField(
            model_name='module',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='qs.officemodule'),
        ),
    ]
